# Generated by Django 5.2 on 2025-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='change@me.com', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
