# Generated by Django 5.2 on 2025-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_email_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
